<% director_uuid = 'CHANGE-ME' %>
<% deployment_name = 'docker' %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: docker
   version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    subnets:
      # network with static ip used for web
      - range: 10.244.8.0/30
        reserved: [10.244.8.1]
        static: [10.244.8.2]
        cloud_properties: {}
      # networks for dynamic ips (db, workers, compilation vms)
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        cloud_properties: {}
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        cloud_properties: {}
      - range: 10.244.8.12/30
        reserved: [10.244.8.13]
        cloud_properties: {}
      - range: 10.244.8.16/30
        reserved: [10.244.8.17]
        cloud_properties: {}
      - range: 10.244.8.20/30
        reserved: [10.244.8.21]
        cloud_properties: {}

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties: {}

jobs:
  - name: docker
    templates:
      - name: docker
      - name: containers
    instances: 1
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
    properties:
      containers:
        - name: redis
          image: "dockerfile/redis"
          command: "--dir /var/lib/redis/ --appendonly yes"
          bind_ports:
            - "6379:6379"
          bind_volumes:
            - "/var/lib/redis"
          entrypoint: "redis-server"
          memory: "256m"
          cpu_shares: 1
          env_vars:
            - "EXAMPLE_VAR=1"